products = [
  {
    '_id': '1',
    'name': 'Full Slimmer Door',
    'image': '/images/airpods.jpg',
    'description': 'Lengkap dengan kusen, kunci bulat, dan engsel',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 755,
    'countInStock': 10,
    'rating': 5.0,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Y28',
    'image': '/images/phone.jpg',
    'description':
      'Lengkap dengan kusen, kunci bulat dan engsel',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 600,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Aluminium 3/4 kaca',
    'image': '/images/camera.jpg',
    'description':
      'Lengkap dengan kusen, kunci gagang dan engsel',
    'brand': 'Cannon',
    'category': 'Electronics',
    'price': 800,
    'countInStock': 5.0,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'm06 Pintu Milenial',
    'image': '/images/playstation.jpg',
    'description':
      'Lengkap dengan kusen, kunci gagang dan engsel',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 720,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Pintu Panel Kustom',
    'image': '/images/mouse.jpg',
    'description':
      'Lengkap dengan kusen, kunci gagang dan engsel',
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 900,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Pintu PVC Daun',
    'image': '/images/alexa.jpg',
    'description':
      'Lengkap dengan kusen, kunci gagang dan engsel',
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 670,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
]
